# SPDX-License-Identifier: MIT
"""Domain profiles catalog for simulation contexts."""
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class DomainProfile:
    name: str = ""
    display_name: str = ""
    description: str = ""
    standards: list[str] = field(default_factory=list)
    safety_levels: list[str] = field(default_factory=list)
    typical_arches: list[str] = field(default_factory=list)
    typical_classes: list[str] = field(default_factory=list)
    test_scenarios: list[str] = field(default_factory=list)


DOMAIN_CATALOG: dict[str, DomainProfile] = {
    "automotive": DomainProfile(
        name="automotive",
        display_name="Automotive / Transportation",
        description="Vehicle ECU and transportation system simulation.",
        standards=["ISO 26262", "AUTOSAR", "SAE J3061"],
        safety_levels=["ASIL-A", "ASIL-B", "ASIL-C", "ASIL-D"],
        typical_arches=["arm", "arm64", "riscv64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["ecu_boot", "can_bus", "ota_update", "diagnostics"],
    ),
    "medical": DomainProfile(
        name="medical",
        display_name="Medical Devices",
        description="Medical device firmware and safety-critical health systems.",
        standards=["IEC 62304", "FDA 510(k)", "ISO 14971"],
        safety_levels=["Class A", "Class B", "Class C"],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["sensor_reading", "alarm_trigger", "data_logging", "ble_pairing"],
    ),
    "industrial": DomainProfile(
        name="industrial",
        display_name="Industrial Automation",
        description="PLC, SCADA, and factory automation simulation.",
        standards=["IEC 61508", "IEC 61131", "OPC UA"],
        safety_levels=["SIL-1", "SIL-2", "SIL-3", "SIL-4"],
        typical_arches=["arm", "x86_64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["plc_cycle", "modbus_comm", "safety_relay", "hmi_display"],
    ),
    "consumer": DomainProfile(
        name="consumer",
        display_name="Consumer Electronics",
        description="Smart home, wearables, and consumer product simulation.",
        standards=["Bluetooth SIG", "Zigbee", "Matter"],
        safety_levels=[],
        typical_arches=["arm", "arm64", "xtensa"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["ble_connect", "wifi_provision", "ota_update", "power_mgmt"],
    ),
    "aerospace": DomainProfile(
        name="aerospace",
        display_name="Aerospace & Avionics",
        description="Avionics, satellite, and space system simulation.",
        standards=["DO-178C", "DO-254", "ARINC 653"],
        safety_levels=["DAL-A", "DAL-B", "DAL-C", "DAL-D", "DAL-E"],
        typical_arches=["arm64", "powerpc", "x86_64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["boot_sequence", "arinc_msg", "redundancy_failover", "time_sync"],
    ),
    "iot": DomainProfile(
        name="iot",
        display_name="Internet of Things",
        description="IoT sensor nodes, gateways, and edge devices.",
        standards=["MQTT", "CoAP", "LwM2M"],
        safety_levels=[],
        typical_arches=["arm", "xtensa", "riscv64"],
        typical_classes=["mcu"],
        test_scenarios=["mqtt_publish", "deep_sleep", "sensor_read", "cloud_connect"],
    ),
    "robotics": DomainProfile(
        name="robotics",
        display_name="Robotics & Motion Control",
        description="Robot controllers, motor drives, and actuator systems.",
        standards=["ROS 2", "ISO 10218", "ISO 13482"],
        safety_levels=["PLd", "PLe"],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["motor_control", "path_planning", "sensor_fusion", "emergency_stop"],
    ),
    "defense": DomainProfile(
        name="defense",
        display_name="Defense & Military",
        description="Defense electronics, radar, and communications.",
        standards=["MIL-STD-810", "MIL-STD-461", "DO-178C"],
        safety_levels=["SIL-3", "SIL-4"],
        typical_arches=["arm64", "powerpc", "x86_64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["secure_boot", "crypto_ops", "radio_comm", "jamming_test"],
    ),
    "energy": DomainProfile(
        name="energy",
        display_name="Energy & Power Systems",
        description="Smart grid, battery management, and power electronics.",
        standards=["IEC 61850", "IEEE 1547", "IEC 62351"],
        safety_levels=["SIL-2", "SIL-3"],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["grid_sync", "battery_charge", "fault_detect", "mppt_control"],
    ),
    "telecom": DomainProfile(
        name="telecom",
        display_name="Telecommunications",
        description="5G baseband, network equipment, and protocol simulation.",
        standards=["3GPP", "O-RAN", "IEEE 802.11"],
        safety_levels=[],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["baseband_init", "packet_switching", "handover", "qos_test"],
    ),
    "aerodynamics": DomainProfile(
        name="aerodynamics",
        display_name="Aerodynamics & CFD",
        description="Computational fluid dynamics and aerodynamic simulation.",
        standards=["NASA CFD", "AIAA", "ISO 5167"],
        safety_levels=["Advisory", "Verification"],
        typical_arches=["x86_64", "arm64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=[
            "laminar_flow", "turbulent_flow", "shock_wave",
            "boundary_layer", "drag_analysis", "lift_curve",
        ],
    ),
    "physiology": DomainProfile(
        name="physiology",
        display_name="Physiology & Biomed Simulation",
        description="Human physiology modeling and biomedical signal simulation.",
        standards=["HL7 FHIR", "IEEE 11073", "ISO 13485"],
        safety_levels=["Class I", "Class II", "Class III"],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc"],
        test_scenarios=["ecg_waveform", "blood_pressure", "respiratory", "drug_response"],
    ),
    "finance": DomainProfile(
        name="finance",
        display_name="Financial Systems",
        description="Trading systems, risk engines, and financial modeling.",
        standards=["FIX Protocol", "ISO 20022", "PCI DSS"],
        safety_levels=["Critical", "High", "Medium"],
        typical_arches=["x86_64", "arm64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["order_matching", "monte_carlo_risk", "latency_test", "market_data"],
    ),
    "weather": DomainProfile(
        name="weather",
        display_name="Weather & Climate Simulation",
        description="Numerical weather prediction and climate modeling.",
        standards=["WMO", "GRIB2", "NetCDF"],
        safety_levels=["Advisory", "Watch", "Warning"],
        typical_arches=["x86_64", "arm64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["hurricane", "forecast_48h", "precipitation", "wind_model", "temperature_grid"],
    ),
    "gaming": DomainProfile(
        name="gaming",
        display_name="Gaming & Real-Time Simulation",
        description="Game physics, rendering pipelines, and real-time simulation.",
        standards=["PhysX", "Vulkan", "OpenXR"],
        safety_levels=[],
        typical_arches=["x86_64", "arm64"],
        typical_classes=["sbc", "devboard"],
        test_scenarios=["physics_sandbox", "collision_test", "render_pipeline", "input_latency"],
    ),
    # ── New domains ──────────────────────────────────────────────────────
    "agriculture": DomainProfile(
        name="agriculture",
        display_name="Agriculture & Precision Farming",
        description="Precision farming, irrigation, and crop management systems.",
        standards=["ISO 11783 (ISOBUS)", "AEF", "AgGateway"],
        safety_levels=["PLa", "PLb"],
        typical_arches=["arm", "riscv32"],
        typical_classes=["mcu", "sensor"],
        test_scenarios=["irrigation_cycle", "soil_monitor", "greenhouse_control", "crop_spray"],
    ),
    "maritime": DomainProfile(
        name="maritime",
        display_name="Maritime & Shipping",
        description="Ship navigation, AIS, and port automation systems.",
        standards=["IMO SOLAS", "IEC 61162", "NMEA 2000"],
        safety_levels=["SIL-1", "SIL-2"],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "gateway"],
        test_scenarios=["autopilot", "ais_broadcast", "port_approach", "storm_response"],
    ),
    "mining": DomainProfile(
        name="mining",
        display_name="Mining & Extraction",
        description="Underground mining, drilling, and mineral extraction systems.",
        standards=["IEC 60079", "ISO 19296", "MSHA"],
        safety_levels=["SIL-2", "SIL-3"],
        typical_arches=["arm", "x86_64"],
        typical_classes=["mcu", "plc", "rtu"],
        test_scenarios=["gas_detection", "ventilation", "drilling", "conveyor_run"],
    ),
    "construction": DomainProfile(
        name="construction",
        display_name="Construction Equipment",
        description="Heavy equipment controllers, crane systems, and site automation.",
        standards=["ISO 15998", "EN 13849", "ISO 19014"],
        safety_levels=["PLc", "PLd", "PLe"],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["crane_lift", "excavation", "load_monitoring", "grade_control"],
    ),
    "retail": DomainProfile(
        name="retail",
        display_name="Retail & Point-of-Sale",
        description="POS terminals, smart shelves, and vending machines.",
        standards=["PCI DSS", "EMV", "NFC Forum"],
        safety_levels=[],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["checkout", "payment_process", "inventory_scan", "self_checkout"],
    ),
    "education": DomainProfile(
        name="education",
        display_name="Education & STEM",
        description="Lab equipment, STEM kits, and educational robotics.",
        standards=["IEEE P2841", "IMS LTI"],
        safety_levels=[],
        typical_arches=["arm", "riscv32", "avr"],
        typical_classes=["mcu", "devboard"],
        test_scenarios=["lab_experiment", "sensor_calibration", "coding_exercise", "data_collection"],
    ),
    "sports": DomainProfile(
        name="sports",
        display_name="Sports & Performance",
        description="Athletic performance tracking, scoring, and wearable systems.",
        standards=["IEEE 802.15.4", "ANT+", "Bluetooth LE"],
        safety_levels=[],
        typical_arches=["arm", "riscv32"],
        typical_classes=["wearable", "sensor"],
        test_scenarios=["sprint_track", "impact_detect", "biometric_monitor", "replay_analysis"],
    ),
    "nuclear": DomainProfile(
        name="nuclear",
        display_name="Nuclear Energy",
        description="Reactor control, radiation monitoring, and fuel management.",
        standards=["IEC 61513", "IEEE 603", "NRC RG 1.152"],
        safety_levels=["SIL-3", "SIL-4"],
        typical_arches=["arm64", "x86_64", "powerpc"],
        typical_classes=["sbc", "safety"],
        test_scenarios=["startup_sequence", "scram", "coolant_monitor", "radiation_alarm"],
    ),
    "railway": DomainProfile(
        name="railway",
        display_name="Railway & Train Control",
        description="Train control systems, signaling, and PTC.",
        standards=["EN 50128", "EN 50129", "ETCS", "PTC"],
        safety_levels=["SIL-3", "SIL-4"],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "safety"],
        test_scenarios=["departure_sequence", "emergency_brake", "signal_change", "crossing_activation"],
    ),
    "smart-city": DomainProfile(
        name="smart-city",
        display_name="Smart City Infrastructure",
        description="Traffic management, street lighting, and urban IoT systems.",
        standards=["FIWARE", "oneM2M", "IEEE 2413"],
        safety_levels=["SIL-1"],
        typical_arches=["arm", "arm64"],
        typical_classes=["gateway", "edge"],
        test_scenarios=["traffic_light_cycle", "parking_mgmt", "street_lighting", "air_quality"],
    ),
    "space": DomainProfile(
        name="space",
        display_name="Space Systems",
        description="Spacecraft, launch vehicles, and deep space exploration.",
        standards=["ECSS-E-ST-40C", "CCSDS", "NASA-STD-8719"],
        safety_levels=["Cat-1", "Cat-2", "Cat-3"],
        typical_arches=["arm64", "powerpc", "riscv64"],
        typical_classes=["sbc", "safety"],
        test_scenarios=["launch_sequence", "orbit_insertion", "attitude_control", "comm_window"],
    ),
    "quantum": DomainProfile(
        name="quantum",
        display_name="Quantum Computing",
        description="Quantum processor control and error correction systems.",
        standards=["IEEE P7131", "QIR"],
        safety_levels=[],
        typical_arches=["x86_64", "arm64"],
        typical_classes=["hpc", "ai-accelerator"],
        test_scenarios=["qubit_init", "gate_sequence", "error_correction", "measurement"],
    ),
    "photonics": DomainProfile(
        name="photonics",
        display_name="Photonics & Optical",
        description="Photonic integrated circuits and optical networking.",
        standards=["IEEE 802.3", "ITU-T G.694"],
        safety_levels=[],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "fpga"],
        test_scenarios=["wavelength_tuning", "modulation", "power_monitor", "fiber_alignment"],
    ),
    "neuromorphic": DomainProfile(
        name="neuromorphic",
        display_name="Neuromorphic Computing",
        description="Spiking neural network processors and brain-inspired chips.",
        standards=["IEEE 2801"],
        safety_levels=[],
        typical_arches=["arm64", "riscv64"],
        typical_classes=["ai-accelerator"],
        test_scenarios=["spike_train", "learning_rule", "pattern_recognition", "energy_benchmark"],
    ),
    "hvac": DomainProfile(
        name="hvac",
        display_name="HVAC & Climate Control",
        description="Heating, ventilation, and air conditioning control systems.",
        standards=["ASHRAE 135 (BACnet)", "ISO 16484", "KNX"],
        safety_levels=["SIL-1"],
        typical_arches=["arm", "riscv32"],
        typical_classes=["mcu", "plc"],
        test_scenarios=["heating_cycle", "cooling_cycle", "ventilation", "energy_saving"],
    ),
    "printing": DomainProfile(
        name="printing",
        display_name="Printing & Additive Manufacturing",
        description="3D printers, inkjet, laser printing systems.",
        standards=["ISO/ASTM 52900", "IEEE 2413"],
        safety_levels=[],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "sbc"],
        test_scenarios=["print_job", "calibration", "filament_change", "bed_leveling"],
    ),
    "elevator": DomainProfile(
        name="elevator",
        display_name="Elevator & Escalator",
        description="Lift control, escalator systems, and vertical transport.",
        standards=["EN 81-20", "ASME A17.1", "ISO 8100"],
        safety_levels=["SIL-3"],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "plc"],
        test_scenarios=["normal_operation", "emergency_stop", "fire_mode", "overload_detect"],
    ),
    "traffic": DomainProfile(
        name="traffic",
        display_name="Traffic Management",
        description="Traffic light controllers, speed cameras, and ITS systems.",
        standards=["NTCIP", "UTMC", "ETSI ITS"],
        safety_levels=["SIL-1", "SIL-2"],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "plc", "rtu"],
        test_scenarios=["signal_cycle", "emergency_preempt", "pedestrian_crossing", "adaptive_timing"],
    ),
    "water": DomainProfile(
        name="water",
        display_name="Water & Wastewater",
        description="Water treatment, distribution, and wastewater management.",
        standards=["IEC 61508", "EPA SCADA", "AWWA"],
        safety_levels=["SIL-1", "SIL-2"],
        typical_arches=["arm", "x86_64"],
        typical_classes=["plc", "rtu"],
        test_scenarios=["filtration", "chlorination", "pump_control", "leak_detection"],
    ),
    "oil-gas": DomainProfile(
        name="oil-gas",
        display_name="Oil & Gas",
        description="Pipeline SCADA, wellhead control, and refinery automation.",
        standards=["API 1164", "IEC 62443", "ISA-95"],
        safety_levels=["SIL-2", "SIL-3"],
        typical_arches=["arm", "x86_64"],
        typical_classes=["plc", "rtu", "safety"],
        test_scenarios=["pipeline_flow", "wellhead_control", "gas_detection", "emergency_shutdown"],
    ),
    "forestry": DomainProfile(
        name="forestry",
        display_name="Forestry & Wildfire",
        description="Forest fire detection, logging equipment, and wildlife monitoring.",
        standards=["ISO 11850", "FAO Guidelines"],
        safety_levels=["PLb", "PLc"],
        typical_arches=["arm", "riscv32"],
        typical_classes=["sensor", "mcu"],
        test_scenarios=["fire_detection", "weather_monitor", "tree_inventory", "wildlife_track"],
    ),
    "fisheries": DomainProfile(
        name="fisheries",
        display_name="Fisheries & Aquaculture",
        description="Fish farming, sonar systems, and marine harvest management.",
        standards=["IMO SOLAS", "FAO CCRF"],
        safety_levels=[],
        typical_arches=["arm", "arm64"],
        typical_classes=["mcu", "sensor"],
        test_scenarios=["sonar_scan", "water_quality", "feeding_cycle", "net_deployment"],
    ),
    "logistics": DomainProfile(
        name="logistics",
        display_name="Logistics & Warehousing",
        description="Warehouse robots, conveyor sorting, and supply chain systems.",
        standards=["GS1", "ISO 28000", "VDA 5050"],
        safety_levels=["PLd"],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "edge"],
        test_scenarios=["pick_and_place", "sorting", "inventory_count", "dock_loading"],
    ),
    "cybersecurity": DomainProfile(
        name="cybersecurity",
        display_name="Cybersecurity & HSM",
        description="Hardware security modules, firewalls, and IDS/IPS systems.",
        standards=["FIPS 140-3", "Common Criteria", "ISO 21434"],
        safety_levels=["EAL4", "EAL5", "EAL6"],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["sbc", "gateway"],
        test_scenarios=["intrusion_detect", "key_generation", "cert_validation", "firewall_test"],
    ),
    "ar-vr": DomainProfile(
        name="ar-vr",
        display_name="AR / VR / Mixed Reality",
        description="Augmented/virtual reality headsets and haptic controllers.",
        standards=["OpenXR", "Khronos", "IEEE 2888"],
        safety_levels=[],
        typical_arches=["arm64", "x86_64"],
        typical_classes=["soc", "wearable"],
        test_scenarios=["head_tracking", "hand_tracking", "room_scan", "render_pipeline"],
    ),
}


def list_domains() -> list[str]:
    return list(DOMAIN_CATALOG.keys())


def get_domain(name: str) -> Optional[DomainProfile]:
    return DOMAIN_CATALOG.get(name)


def suggest_platforms(domain: str, registry) -> list:
    profile = get_domain(domain)
    if profile is None:
        return []
    results = registry.filter(domain=domain)
    if not results:
        results = [p for p in registry.all()
                    if p.arch in profile.typical_arches
                    or p.platform_class in profile.typical_classes]
    return results
