# SPDX-License-Identifier: MIT
# Copyright (c) 2026 EoS Project
"""Code generation from simulation models."""
import os


class CodeGenerator:
    """Generate embedded C code stubs from EoSim platform definitions."""

    def __init__(self, output_dir='generated'):
        self.output_dir = output_dir

    def generate_peripheral_driver(self, peripheral, language='c'):
        name = peripheral.name
        base = peripheral.base
        header = f"""/* Auto-generated by EoSim CodeGen */
#ifndef {name.upper()}_H
#define {name.upper()}_H

#include <stdint.h>

#define {name.upper()}_BASE  0x{base:08X}

void {name}_init(void);
uint32_t {name}_read(uint32_t offset);
void {name}_write(uint32_t offset, uint32_t value);

#endif /* {name.upper()}_H */
"""
        source = f"""/* Auto-generated by EoSim CodeGen */
#include "{name}.h"

static volatile uint32_t *const {name}_regs = (uint32_t *){name.upper()}_BASE;

void {name}_init(void) {{
    /* TODO: Initialize {name} peripheral */
}}

uint32_t {name}_read(uint32_t offset) {{
    return {name}_regs[offset / 4];
}}

void {name}_write(uint32_t offset, uint32_t value) {{
    {name}_regs[offset / 4] = value;
}}
"""
        return {'header': header, 'source': source}

    def write_files(self, files_dict):
        os.makedirs(self.output_dir, exist_ok=True)
        written = []
        for fname, content in files_dict.items():
            path = os.path.join(self.output_dir, fname)
            with open(path, 'w') as f:
                f.write(content)
            written.append(path)
        return written
